### PR TITLE
Upgrade to ASM 7.3.1 to support Java 14

### PR DESCRIPTION
**Pull request by runeflobakk**
## Changes
Upgrade ASM from 7.1 to 7.3.1, in order to support Java 14 bytecode. Verified works with maven-dependency-plugin v3.1.1 analyze-goal on an own Java 14 project.

This is an equivalent PR to #6. As I consider this a [trivial change](https://github.com/apache/maven-dependency-analyzer#making-trivial-changes), I have not opened a JIRA issue.

---

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MSHARED) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes. Also be sure having selected the correct component.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MSHARED-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MSHARED-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by khmarbaise** [comment]
Lets see what CI says...

**Comment by runeflobakk** [comment]
Should I add JDK 13 and 14 to the Jenkinsfile, as in [04cd223](https://github.com/apache/maven-dependency-analyzer/commit/04cd223523b2f45400746e6d24d40044a0b34fee#diff-58231b16fdee45a03a4ee3cf94a9f2c3R20)?

**Comment by khmarbaise** [comment]
No thanks. We should use the defaults instead of manually defining the JDK versions.. trying on another branch first ...

**Comment by khmarbaise** [comment]
So merged to master. Thank you for your contribution.

**Pull request closed without merging**
