### PR TITLE
[MDEP-708] dependency:analyze should recommend narrower scope where possible

### PR DESCRIPTION
**Pull request by ian-lavallee**
Fixes issue with test dependencies where we consider runtime scope to not be included as test.

### CODE REVIEW

**Comment by ian-lavallee** [comment]
@elharo

**Comment by ian-lavallee** [comment]
@elharo I'm not a committer so I need you to merge this when you have a chance.

**Comment by ian-lavallee** [comment]
We probably want to push a release out again for dependency-analyzer once this is in too

**Comment by elharo** [comment]
Test passed: https://builds.apache.org/job/maven-box/job/maven-dependency-analyzer/job/mybranch/

**Comment by ian-lavallee** [comment]
Test added and the integration test and naming for the html table constructed by analyzeReportView in maven-dependency-plugin have also been updated.

**Comment by elharo** [comment]
https://builds.apache.org/job/maven-box/job/maven-dependency-analyzer/job/mybranch/

**Pull request merged**
