### PR TITLE
[MSHARED-870] - Upgrade asm to 8.0.1

### PR DESCRIPTION
**Pull request by adangel**
Upgrades again from 8.0.0 -> 8.0.1
Also uses the new Opcodes constant, so that the new features can actually be used.

Note: we could go to ASM9_EXPERIMENTAL to support class files with preview features as well.

Note2: I'm reusing MSHARED-870, since maven-dependency-analyzer 1.1.2 is not released yet. I'll reopen that issue.

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MSHARED) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes. Also be sure having selected the correct component.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MSHARED-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MSHARED-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by slachiewicz** [comment]
There are few more references to Opcode.ASM7 - should we also update them ?

**Comment by adangel** [comment]
Probably yes, I'll update the other references. It worked for me without these, but it of course depends on the class files/features, that are analyzed.

**Comment by adangel** [comment]
Done in e86708327d0f39d7d1ce3fc0a1a1ef7f085481f2

**Comment by jira-importer** [comment]
Resolve #196

**Pull request merged**
