### PR TITLE
MSHARED-1038: Inner classes are in same compilation unit as container class

### PR DESCRIPTION
**Pull request by chonton**
Fold inner class dependency into container class

 - [ x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
Thanks. Will be good to add some of test. Unit or IT, of course we can extends existing one.

**Comment by chonton** [comment]
unit tests added.

**Review by slawekjaranowski — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
@chonton please resolve conflicts

**Comment by slawekjaranowski** [comment]
sorry - maybe I merged in wrong order ... please resolve conflicts again ...

**Pull request merged**
